# Lab 1: Numpy Practice

## Mục tiêu
- Nắm vững các thao tác cơ bản với mảng NumPy
- Hiểu và áp dụng broadcasting
- Thực hành với dữ liệu thực tế
- Tối ưu hóa code với NumPy

## Phần 1: Array Basics và Indexing

### Bài 1.1: Tạo và thao tác với mảng

In [ ]:
import numpy as np

# TODO: Tạo mảng 1D chứa các số từ 0 đến 99
arr_1d = np.arange(100)
# dùng kỹ thuật slicing để in 10 phần tử đầu tiên
print("Mang 1D:", arr_1d[:10], "...")  # In 10 phần tử đầu tiên (in ra phần tử từ 0 - 9)

# TODO: Reshape mảng trên thành mảng 2D kích thước 10x10
arr_2d = arr_1d.reshape(10, 10)

# TODO: Lấy phần tử ở hàng 3, cột 5
element = arr_2d[3, 5]

# TODO: Lấy hàng thứ 5
#dùng kỹ thuật slicing để lấy toàn bộ phần tử trong hàng 5
row_5 = arr_2d[5, :] #hoặc arr_2d[5]

# TODO: Lấy cột thứ 7
col_7 = arr_2d[:, 7] #tất cả các hàng , cột 7

# TODO: Lấy subarray 3x3 từ góc trên bên trái
subarray = arr_2d[0:3, 0:3] # hàng lấy từ 0 đến 3-1, cột lấy từ 0 đến 3-1

print("Mảng 2D:\n", arr_2d)
print("\nPhần tử [3,5]:", element)
print("\nHàng 5:", row_5)
print("\nCột 7:", col_7)
print("\nSubarray 3x3:\n", subarray)

Mang 1D: [0 1 2 3 4 5 6 7 8 9] ...
Mảng 2D:
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]

Phần tử [3,5]: 35

Hàng 5: [50 51 52 53 54 55 56 57 58 59]

Cột 7: [ 7 17 27 37 47 57 67 77 87 97]

Subarray 3x3:
 [[ 0  1  2]
 [10 11 12]
 [20 21 22]]


- **np.arange** là hàm NumPy dùng để tạo mảng 1D chứa các số theo dãy số họ có khoảng cách đều nhau

- **reshape()** biến đổi hình dạng (shape) của mảng từ 1 chiều thành nhiều chiều mà **Không làm thay đổi dữ liệu gốc**

- câu lệnh **indexing[a,b]** dùng để truy cập phần tử cụ thể trng mảng đa chiều bằng chỉ 
- câu lệnh **Slicing hàng[a]** lấy toàn bộ hàng từ mảng a(2D)
- câu lệnh **Slicing cột[:, a] hoặc [a]** lấy toàn bộ cột a (2D)

### Bài 1.2: Boolean Indexing

In [ ]:
# Tạo mảng ngẫu nhiên
np.random.seed(42)
data = np.random.randn(100)

# TODO: Tìm tất cả các phần tử > 0
positive_elements = data[data > 0] #data > 0: tạo một mảng boolean với true ở các vi trí phần tử >0
#data[data >0] sử dụng boolean indexing để lọc ra chỉ những phần tử thoả mãn điều kiện

# TODO: Tìm tất cả các phần tử trong khoảng [-1, 1]
range_elements = data[(data >= -1) & (data <= 1)] #sử dụng toán tử & để kết hợp hai điều kiện boolean

# TODO: Thay thế tất cả các phần tử âm bằng 0
data_modified = data.copy() # tạo bản sao để giữ nguyên mảng gốc
data_modified[data_modified < 0] = 0 #gán giá trị 0 cho các phần tử âm sử dụng boolean indexing

print("Số phần tử dương:", len(positive_elements))
print("Số phần tử trong [-1,1]:", len(range_elements))
print("Số phần tử âm đã thay thế:", np.sum(data < 0))

Số phần tử dương: 46
Số phần tử trong [-1,1]: 72
Số phần tử âm đã thay thế: 54


## Phần 2: Array Operations và Broadcasting

### Bài 2.1: Các phép toán cơ bản

In [ ]:
# Tạo hai mảng 2D
A = np.random.randint(0, 10, size=(4, 5)) # gian ngẫu nhiên từ 0 đến 9 vao mảng 4x5
B = np.random.randint(0, 10, size=(4, 5))

print("Mảng A:\n", A)
print("\nMảng B:\n", B)

# TODO: Tính tổng từng phần tử
element_sum = A + B

# TODO: Tính tích từng phần tử
element_product = A * B

# TODO: Tính ma trận tích (dot product)
# Hint: Cần transpose một trong hai mảng
matrix_product = np.dot(A, B.T) # hoặc A @ B.T

# TODO: Tính mean, std, min, max của mảng A theo các trục
mean_all = np.mean(A)  # Mean toàn mảng
mean_rows = np.mean(A, axis=1)  # Trung bình theo hàng
mean_cols = np.mean(A, axis=0)  # Trung bình theo cột

#tính thêm std, min, max
std_all = np.std(A) # độ lệch chuẩn toàn mảng
min_all = np.min(A)
max_all = np.max(A)


print("\nTổng từng phần tử:\n", element_sum)
print("\nTích từng phần tử:\n", element_product)
print("\nMean toàn mảng:", mean_all)
print("Mean theo hàng:", mean_rows)
print("Mean theo cột:", mean_cols)
print("Std toàn mảng:", std_all)
print("Min toàn mảng:", min_all)
print("Max toàn mảng:", max_all)

Mảng A:
 [[9 7 1 4 6]
 [7 0 5 0 1]
 [0 4 9 8 5]
 [0 0 1 8 2]]

Mảng B:
 [[0 4 6 5 0]
 [4 4 5 2 4]
 [6 4 4 4 9]
 [9 2 0 4 8]]

Tổng từng phần tử:
 [[ 9 11  7  9  6]
 [11  4 10  2  5]
 [ 6  8 13 12 14]
 [ 9  2  1 12 10]]

Tích từng phần tử:
 [[ 0 28  6 20  0]
 [28  0 25  0  4]
 [ 0 16 36 32 45]
 [ 0  0  0 32 16]]

Mean toàn mảng: 3.85
Mean theo hàng: [5.4 2.6 5.2 2.2]
Mean theo cột: [4.   2.75 4.   5.   3.5 ]
Std toàn mảng: 3.2905166767545797
Min toàn mảng: 0
Max toàn mảng: 9


### Bài 2.2: Broadcasting

In [22]:
# Tạo ma trận và vector
matrix = np.random.randn(4, 3)
vector = np.array([1, 2, 3])

print("Ma trận (4x3):\n", matrix)
print("\nVector (3,):", vector)

# TODO: Cộng vector vào mỗi hàng của ma trận sử dụng broadcasting
result_broadcast = matrix + vector  # broadcasting tự động mở rộng vector

# TODO: Nhân mỗi cột của ma trận với [1, 2, 3, 4] sử dụng broadcasting
# Hint: Cần reshape vector thành (4, 1)
col_multiplier = np.array([1, 2, 3, 4]).reshape(4, 1)
result_col = matrix * col_multiplier
print("\nNhan theo cot:\n", result_col)

# TODO: Chuẩn hóa ma trận (normalize) - trừ mean và chia cho std theo mỗi cột
normalized_matrix = np.mean(matrix, axis=0)
std_col = matrix * col_multiplier
std_col = np.std(matrix, axis=0)
normalized_matrix = (matrix - normalized_matrix) / std_col
print("\nMa trận chuẩn hóa:\n", normalized_matrix)


print("\nKết quả broadcast:\n", result_broadcast)
print("\nNhân theo cột:\n", result_col)
print("\nMa trận chuẩn hóa:\n", normalized_matrix)

Ma trận (4x3):
 [[ 1.02657985  0.16608813 -1.02038325]
 [-0.26909444  1.48904517  0.87782517]
 [-0.43365033 -0.34230864 -1.7308731 ]
 [ 1.44433879  0.88606356 -0.13707782]]

Vector (3,): [1 2 3]

Nhan theo cot:
 [[ 1.02657985  0.16608813 -1.02038325]
 [-0.53818888  2.97809035  1.75565034]
 [-1.30095098 -1.02692592 -5.19261931]
 [ 5.77735517  3.54425424 -0.54831128]]

Ma trận chuẩn hóa:
 [[ 0.72241613 -0.55110101 -0.53009619]
 [-0.87888028  1.34936429  1.41335411]
 [-1.08225142 -1.28142738 -1.25751986]
 [ 1.23871557  0.48316411  0.37426193]]

Kết quả broadcast:
 [[2.02657985 2.16608813 1.97961675]
 [0.73090556 3.48904517 3.87782517]
 [0.56634967 1.65769136 1.2691269 ]
 [2.44433879 2.88606356 2.86292218]]

Nhân theo cột:
 [[ 1.02657985  0.16608813 -1.02038325]
 [-0.53818888  2.97809035  1.75565034]
 [-1.30095098 -1.02692592 -5.19261931]
 [ 5.77735517  3.54425424 -0.54831128]]

Ma trận chuẩn hóa:
 [[ 0.72241613 -0.55110101 -0.53009619]
 [-0.87888028  1.34936429  1.41335411]
 [-1.08225142 

## Phần 3: Ứng dụng thực tế

### Bài 3.1: Xử lý dữ liệu sinh viên

In [ ]:
# Dữ liệu điểm của 50 sinh viên, 5 môn học
np.random.seed(42)
scores = np.random.randint(0, 101, size=(50, 5))

print("Dữ liệu điểm (50 sinh viên x 5 môn):")
print(scores[:5])  # Hiển thị 5 sinh viên đầu

# TODO: Tính điểm trung bình của mỗi sinh viên
student_averages = np.mean(scores, axis=1)

# TODO: Tìm sinh viên có điểm TB cao nhất
best_student_idx = np.argmax(student_averages)

# TODO: Tính điểm trung bình của mỗi môn
subject_averages = np.mean(scores, axis=0)

# TODO: Tìm môn khó nhất (TB thấp nhất)
hardest_subject = np.argmin(subject_averages)

# TODO: Đếm số sinh viên đạt điểm >= 80 ở mỗi môn
excellent_counts = np.sum(scores >= 80, axis=0)

# TODO: Tạo mảng boolean cho sinh viên có TB >= 70
passed_students = student_averages >= 70

print("\nĐiểm TB cao nhất:", student_averages[best_student_idx])
print("Điểm TB các môn:", subject_averages)
print("Số SV xuất sắc mỗi môn:", excellent_counts)
print("Tỷ lệ đậu:", np.sum(passed_students) / len(scores) * 100, "%")

### Bài 3.2: Ma trận và Linear Algebra

In [ ]:
# TODO: Tạo ma trận 5x5 với giá trị ngẫu nhiên
matrix = None

# TODO: Tính định thức (determinant)
det = None

# TODO: Tính ma trận nghịch đảo (nếu có)
try:
    inv_matrix = None
    # Kiểm tra: A @ A^(-1) = I
    identity_check = None
    print("Ma trận nghịch đảo tồn tại")
except:
    print("Ma trận không khả nghịch")

# TODO: Tính eigenvalues và eigenvectors
eigenvalues, eigenvectors = None

# TODO: Tính ma trận transpose
transpose = None

print("Định thức:", det)
print("\nEigenvalues:", eigenvalues)

## Phần 4: Image Processing với NumPy

### Bài 4.1: Xử lý ảnh cơ bản

In [ ]:
import matplotlib.pyplot as plt
from PIL import Image

# Load ảnh
img = np.array(Image.open('cat.jpg'))

print("Kích thước ảnh:", img.shape)

# TODO: Chuyển ảnh sang grayscale
# Công thức: 0.299*R + 0.587*G + 0.114*B
gray = None

# TODO: Lật ảnh theo chiều ngang
flipped_h = None

# TODO: Lật ảnh theo chiều dọc  
flipped_v = None

# TODO: Crop ảnh - lấy phần giữa 200x200 pixels
h, w = img.shape[:2]
center_h, center_w = h // 2, w // 2
cropped = None

# TODO: Tăng độ sáng thêm 50
brightened = None

# Hiển thị kết quả
fig, axes = plt.subplots(2, 3, figsize=(15, 10))
axes[0, 0].imshow(img)
axes[0, 0].set_title('Original')
axes[0, 1].imshow(gray, cmap='gray')
axes[0, 1].set_title('Grayscale')
axes[0, 2].imshow(flipped_h)
axes[0, 2].set_title('Flipped Horizontal')
axes[1, 0].imshow(flipped_v)
axes[1, 0].set_title('Flipped Vertical')
axes[1, 1].imshow(cropped)
axes[1, 1].set_title('Cropped')
axes[1, 2].imshow(brightened)
axes[1, 2].set_title('Brightened')
plt.tight_layout()
plt.show()

### Bài 4.2: Image Filtering

In [ ]:
# Tạo một kernel Gaussian blur 5x5
def gaussian_kernel(size=5, sigma=1.0):
    # TODO: Tạo Gaussian kernel
    # Hint: sử dụng công thức Gaussian 2D
    kernel = None
    return kernel / np.sum(kernel)  # Normalize

# TODO: Implement convolution thủ công
def apply_filter(image, kernel):
    # TODO: Áp dụng kernel lên ảnh grayscale
    # Hint: lặp qua các pixel và tính tổng tích chập
    filtered = None
    return filtered

# Áp dụng filter
kernel = gaussian_kernel()
blurred = apply_filter(gray, kernel)

# Hiển thị
plt.figure(figsize=(10, 5))
plt.subplot(121)
plt.imshow(gray, cmap='gray')
plt.title('Original')
plt.subplot(122)
plt.imshow(blurred, cmap='gray')
plt.title('Blurred')
plt.show()

## Phần 5: Data Analysis

### Bài 5.1: Phân tích dữ liệu nhiệt độ

In [ ]:
# Dữ liệu nhiệt độ hàng ngày trong 365 ngày (°C)
np.random.seed(42)
# Tạo nhiệt độ theo mùa
days = np.arange(365)
temp = 20 + 10 * np.sin(2 * np.pi * days / 365) + np.random.randn(365) * 3

# TODO: Tính nhiệt độ trung bình
avg_temp = None

# TODO: Tìm ngày nóng nhất và lạnh nhất
hottest_day = None
coldest_day = None

# TODO: Tính nhiệt độ TB theo từng tháng (30 ngày/tháng)
monthly_avg = None

# TODO: Đếm số ngày > 25°C
hot_days = None

# TODO: Tính độ lệch chuẩn của nhiệt độ
temp_std = None

print(f"Nhiệt độ TB: {avg_temp:.2f}°C")
print(f"Ngày nóng nhất: ngày {hottest_day}, {temp[hottest_day]:.2f}°C")
print(f"Ngày lạnh nhất: ngày {coldest_day}, {temp[coldest_day]:.2f}°C")
print(f"Số ngày > 25°C: {hot_days}")
print(f"Độ lệch chuẩn: {temp_std:.2f}°C")

# Visualize
plt.figure(figsize=(15, 5))
plt.plot(days, temp, alpha=0.7, label='Nhiệt độ hàng ngày')
plt.axhline(y=avg_temp, color='r', linestyle='--', label='Trung bình')
plt.xlabel('Ngày')
plt.ylabel('Nhiệt độ (°C)')
plt.title('Nhiệt độ trong năm')
plt.legend()
plt.grid(True)
plt.show()

## Phần 6: Advanced Operations

### Bài 6.1: Fancy Indexing và Sorting

In [ ]:
# Tạo mảng random
np.random.seed(42)
data = np.random.randint(0, 100, size=20)

print("Dữ liệu gốc:", data)

# TODO: Sắp xếp mảng tăng dần
sorted_data = None

# TODO: Lấy indices của 5 phần tử lớn nhất
top5_indices = None

# TODO: Lấy giá trị của 5 phần tử lớn nhất
top5_values = None

# TODO: Tạo mảng boolean cho các số chẵn
is_even = None

# TODO: Lấy tất cả các số chẵn
even_numbers = None

print("\nMảng đã sắp xếp:", sorted_data)
print("Top 5 values:", top5_values)
print("Top 5 indices:", top5_indices)
print("Các số chẵn:", even_numbers)

### Bài 6.2: Vectorization Performance

In [ ]:
import time

# Tạo mảng lớn
n = 1000000
a = np.random.rand(n)
b = np.random.rand(n)

# Cách 1: Sử dụng vòng lặp Python
start = time.time()
c = np.zeros(n)
for i in range(n):
    c[i] = a[i] + b[i]
loop_time = time.time() - start

# Cách 2: Vectorization
start = time.time()
# TODO: Thực hiện phép cộng bằng vectorization
c_vec = None
vec_time = time.time() - start

print(f"Thời gian vòng lặp: {loop_time:.4f}s")
print(f"Thời gian vectorization: {vec_time:.4f}s")
print(f"Speedup: {loop_time/vec_time:.1f}x")

# TODO: Implement dot product theo 2 cách và so sánh
# Cách 1: Vòng lặp
start = time.time()
result_loop = 0
# TODO: Tính dot product bằng vòng lặp
loop_dot_time = time.time() - start

# Cách 2: NumPy
start = time.time()
# TODO: Tính dot product bằng NumPy
result_np = None
np_dot_time = time.time() - start

print(f"\nDot product loop time: {loop_dot_time:.4f}s")
print(f"Dot product NumPy time: {np_dot_time:.4f}s")
print(f"Speedup: {loop_dot_time/np_dot_time:.1f}x")

## Phần 7: Mini Project - K-Nearest Neighbors

### Implement thuật toán KNN từ đầu sử dụng NumPy

In [ ]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

# Load Iris dataset
iris = load_iris()
X, y = iris.data, iris.target

# Chia train/test
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

def euclidean_distance(x1, x2):
    """Tính khoảng cách Euclidean giữa hai vector"""
    # TODO: Implement
    return None

def knn_predict(X_train, y_train, X_test, k=3):
    """Predict labels cho X_test sử dụng KNN"""
    predictions = []
    
    for test_point in X_test:
        # TODO: Tính khoảng cách đến tất cả training points
        distances = None
        
        # TODO: Lấy indices của k nearest neighbors
        k_indices = None
        
        # TODO: Lấy labels của k neighbors
        k_labels = None
        
        # TODO: Predict label (most common)
        prediction = None
        predictions.append(prediction)
    
    return np.array(predictions)

# Predict
y_pred = knn_predict(X_train, y_train, X_test, k=3)

# TODO: Tính accuracy
accuracy = None

print(f"Accuracy: {accuracy * 100:.2f}%")

# TODO: Tạo confusion matrix
confusion_matrix = None

print("\nConfusion Matrix:")
print(confusion_matrix)

## Bài tập nâng cao

### Bài 8.1: Implement Convolution 2D

In [ ]:
def conv2d(image, kernel):
    """Implement 2D convolution"""
    # TODO: Implement
    # Hint: 
    # 1. Lấy kích thước image và kernel
    # 2. Tạo output array
    # 3. Lặp qua các pixel
    # 4. Áp dụng kernel tại mỗi vị trí
    pass

# Test với edge detection kernel
edge_kernel = np.array([[-1, -1, -1],
                        [-1,  8, -1],
                        [-1, -1, -1]])

# Áp dụng
edges = conv2d(gray, edge_kernel)

plt.figure(figsize=(10, 5))
plt.subplot(121)
plt.imshow(gray, cmap='gray')
plt.title('Original')
plt.subplot(122)
plt.imshow(edges, cmap='gray')
plt.title('Edge Detection')
plt.show()

### Bài 8.2: Implement Simple Neural Network Forward Pass

In [ ]:
def sigmoid(x):
    # TODO: Implement sigmoid activation
    return None

def relu(x):
    # TODO: Implement ReLU activation
    return None

# Tạo một simple neural network: 4 -> 8 -> 3
np.random.seed(42)
W1 = np.random.randn(4, 8) * 0.1
b1 = np.zeros(8)
W2 = np.random.randn(8, 3) * 0.1
b2 = np.zeros(3)

# Input (10 samples, 4 features)
X = np.random.randn(10, 4)

# TODO: Forward pass
# Layer 1
z1 = None  # Linear transformation
a1 = None  # Activation (ReLU)

# Layer 2
z2 = None  # Linear transformation
a2 = None  # Activation (sigmoid)

print("Input shape:", X.shape)
print("Hidden layer output shape:", a1.shape)
print("Final output shape:", a2.shape)
print("\nOutput (first 3 samples):")
print(a2[:3])